<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5M0b0Ux\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5M0b0Ux/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container5M0b0Ux.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container5M0b0Ux\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container5M0b0Ux\App_KernelProdContainer([
    'container.build_hash' => '5M0b0Ux',
    'container.build_id' => 'd5221cfb',
    'container.build_time' => 1588152796,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5M0b0Ux');
