<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOAAbHFg\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOAAbHFg/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOAAbHFg.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOAAbHFg\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOAAbHFg\App_KernelProdContainer([
    'container.build_hash' => 'OAAbHFg',
    'container.build_id' => '4ae57d97',
    'container.build_time' => 1593157180,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOAAbHFg');
