<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home_unlogged' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::unloggedHome'], [], [['text', '/']], [], []],
    'home_logged' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::index'], [], [['text', '/operations']], [], []],
    'operation_create' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::form'], [], [['text', '/operation/new']], [], []],
    'operation_edit' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::form'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/operation']], [], []],
    'operation_show' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/operation']], [], []],
    'operation_delete' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/operation']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
