<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home_unlogged' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::unloggedHome'], [], [['text', '/']], [], []],
    'home_logged' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::index'], [], [['text', '/operations']], [], []],
    'operation_create' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::form'], [], [['text', '/operation/new']], [], []],
    'operation_edit' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::form'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/operation']], [], []],
    'operation_show' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/operation']], [], []],
    'operation_delete' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/operation']], [], []],
    'category_show' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::showCategory'], [], [['text', '/category']], [], []],
    'category_add' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::addCategory'], [], [['text', '/cateogry/new']], [], []],
    'category_edit' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::addCategory'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], []],
    'category_delete' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::deleteCategory'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], []],
    'payementMethod_show' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::showPayementMethod'], [], [['text', '/payementMethod']], [], []],
    'payementMethod_add' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::addPayementMethod'], [], [['text', '/payementMethod/new']], [], []],
    'payementMethod_edit' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::addPayementMethod'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/payementMethod']], [], []],
    'payementMethod_delete' => [['id'], ['_controller' => 'App\\Controller\\BankOperationsController::deletePayementMethod'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/payementMethod']], [], []],
    'statistics' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::stats'], [], [['text', '/statistics']], [], []],
    'operationsJsonified' => [[], ['_controller' => 'App\\Controller\\BankOperationsController::operationsAPI'], [], [['text', '/operationsJsonified']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
