<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9662464f.js',
                '/build/app.7c270053.js',
            ],
            'css' => [
                '/build/app.ae8e98b1.css',
            ],
        ],
    ],
],

]];
