<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9662464f.js',
                '/build/0.e3b88ef0.js',
                '/build/app.151f044e.js',
            ],
            'css' => [
                '/build/app.88feed74.css',
            ],
        ],
    ],
],

]];
