<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOMZurxi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOMZurxi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOMZurxi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOMZurxi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOMZurxi\App_KernelDevDebugContainer([
    'container.build_hash' => 'OMZurxi',
    'container.build_id' => 'afd21ecf',
    'container.build_time' => 1592939665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOMZurxi');
